import { access, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import StyleDictionary from 'style-dictionary';

/**
 * Every Goshi tokens package (foundations, consumer, enterprise) builds its
 * source JSON through this same pipeline, so token naming/output shape stays
 * identical across the whole design system. See
 * docs/architecture/0003-token-pipeline-style-dictionary.md.
 */

function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

/**
 * Builds a nested object mirroring each token's resolved path, e.g. a token
 * with path `['con', 'color', 'background', 'primary']` becomes
 * `tree.con.color.background.primary`. Built from `dictionary.allTokens`
 * (not `dictionary.tokens`) because Style Dictionary's per-file `filter`
 * option is only guaranteed to filter `allTokens` — the nested `tokens` tree
 * on the format callback is not reliably pre-filtered.
 *
 * @param {object[]} allTokens
 * @param {string[]} [stripPrefix] - leading path segments to drop, e.g. `['con']`
 *   so a `con.color.background.primary` token lands at `tree.color.background.primary`
 *   in the generated module (the `con`/`ent` name comes from the export itself).
 */
function buildNestedTree(allTokens, stripPrefix = []) {
  const root = {};
  for (const token of allTokens) {
    const path = token.path.slice(0, stripPrefix.length).every((seg, i) => seg === stripPrefix[i])
      ? token.path.slice(stripPrefix.length)
      : token.path;
    let node = root;
    for (let i = 0; i < path.length - 1; i += 1) {
      const key = path[i];
      node[key] = node[key] ?? {};
      node = node[key];
    }
    node[path[path.length - 1]] = token.value;
  }
  return root;
}

let formatRegistered = false;

/**
 * Registers the `nested/module` format: emits a nested object mirroring the
 * token path (e.g. `color.background.primary`) instead of Style Dictionary's
 * default flattened/camel-cased names. This is what lets consumers write
 * `con.color.background.primary` / `ent.color.background.primary`.
 */
function ensureNestedModuleFormatRegistered() {
  if (formatRegistered) return;
  StyleDictionary.registerFormat({
    name: 'nested/module',
    format: ({ dictionary, options }) => {
      const exportName = options.exportName ?? 'tokens';
      const tree = buildNestedTree(dictionary.allTokens, options.stripPrefix ?? []);
      return (
        '/**\n' +
        ' * Auto-generated by Style Dictionary. Do not edit directly —\n' +
        ' * edit the token sources under `src/` and run `pnpm tokens:build`.\n' +
        ' */\n\n' +
        `export const ${exportName} = ${JSON.stringify(tree, null, 2)} as const;\n\n` +
        `export type ${capitalize(exportName)} = typeof ${exportName};\n\n` +
        `export default ${exportName};\n`
      );
    },
  });
  formatRegistered = true;
}

/**
 * Builds one token "variant" (e.g. primitives, or semantic/light, or a
 * typography scale) into a nested TS module and, optionally, a CSS custom
 * properties file.
 *
 * @param {object} opts
 * @param {string} opts.label - human-readable name for build logging
 * @param {string[]} opts.source - Style Dictionary source globs
 * @param {(token: object) => boolean} [opts.filter] - restrict output to a subset of `source`
 * @param {string} opts.exportName - name of the exported const, e.g. `conLight`, `primitives`
 * @param {string[]} [opts.stripPrefix] - leading path segments to drop from the output tree
 * @param {string} [opts.tsBuildPath] - output dir for the generated `.ts` module
 * @param {string} [opts.cssBuildPath] - output dir for the generated `.css` file
 * @param {string} [opts.cssFile] - CSS filename; omit to skip CSS output entirely
 * @param {string} [opts.cssSelector] - CSS selector to scope the custom properties to
 * @param {string} [opts.prefix] - CSS custom property prefix (default `goshi`)
 */
export async function buildTokenVariant({
  label,
  source,
  filter,
  exportName,
  stripPrefix = [],
  tsBuildPath = 'src/generated/',
  cssBuildPath = 'build/css/',
  cssFile,
  cssSelector = ':root',
  prefix = 'goshi',
}) {
  ensureNestedModuleFormatRegistered();

  const sd = new StyleDictionary({
    source,
    platforms: {
      ts: {
        transformGroup: 'js',
        buildPath: tsBuildPath,
        files: [
          {
            destination: `${exportName}.ts`,
            format: 'nested/module',
            filter,
            options: { exportName, stripPrefix },
          },
        ],
      },
      ...(cssFile
        ? {
            css: {
              transformGroup: 'css',
              prefix,
              buildPath: cssBuildPath,
              files: [
                {
                  destination: cssFile,
                  format: 'css/variables',
                  filter,
                  options: { selector: cssSelector, outputReferences: true },
                },
              ],
            },
          }
        : {}),
    },
  });

  await sd.hasInitialized;
  await sd.buildAllPlatforms();

  // Style Dictionary silently skips *calling the format at all* (and so
  // never writes the file) when zero tokens match its filter — it doesn't
  // invoke `nested/module` with an empty `allTokens`, it just no-ops. That
  // happens today for @goshi/enterprise-typography, which has no tokens yet
  // (see docs/architecture/0004-figma-sync-status.md). Detect that by
  // checking what actually landed on disk — not by re-deriving "would any
  // tokens have matched" from the StyleDictionary instance, whose top-level
  // token shape isn't the same as the fully-resolved `dictionary.allTokens`
  // the format callback receives — and write the module ourselves so the
  // package's hand-written `src/index.ts` always has something to import.
  const tsFile = path.join(tsBuildPath, `${exportName}.ts`);
  const tsFileExists = await access(tsFile)
    .then(() => true)
    .catch(() => false);
  if (!tsFileExists) {
    await mkdir(path.dirname(tsFile), { recursive: true });
    await writeFile(tsFile, emptyModuleSource(exportName));
  }

  console.log(`✓ built ${label}`);
}

function emptyModuleSource(exportName) {
  return (
    '/**\n' +
    ' * Auto-generated by Style Dictionary. Do not edit directly —\n' +
    ' * edit the token sources under `src/` and run `pnpm tokens:build`.\n' +
    ' *\n' +
    ' * No tokens matched this variant\'s filter, so there is nothing to\n' +
    ' * nest — Style Dictionary itself skips writing a file in this case.\n' +
    ' */\n\n' +
    `export const ${exportName} = {} as const;\n\n` +
    `export type ${capitalize(exportName)} = typeof ${exportName};\n\n` +
    `export default ${exportName};\n`
  );
}
